### ISSUE TITLE
Add support for i18n in web client

### ISSUE THREAD

**Issue by donkeysharp** [donkeysharp/gocho#11]
The idea is to detect client's locale and display content based on the files something like: `en.json`, `es.json`, `it.json`. One way to detect browser's language is with the help of `navigator.languages` or `navigator.language`

**Comment by aladhims** [comment]
Hello is this issue still relevant?

**Comment by donkeysharp** [comment]
hey @aladhims yes, it is still relevant. Currently Gocho only displays its dashboard page in pure english, it would be great if it could display based on client's language with the option to choose :)

**Comment by aladhims** [comment]
I only know Bahasa Indonesia and English, I'm probably only able to add Bahasa to support it, is that ok?

**Comment by donkeysharp** [comment]
of course! that will be a great start because based on your work it should be easy to support new languages

**Comment by donkeysharp** [comment]
Solved in https://github.com/donkeysharp/gocho/pull/19
