### ISSUE TITLE
Multiple users and concurrency

### ISSUE THREAD

**Issue by gedw99** [donkeysharp/gocho#8]
What's the story on many users editing the same file.
Would be good to add that to the readme. I am guessing it's LWW ( last write wins)

This project reminds me of automerge. It's on GitHub and allows concurrent editing of the same documents with offline / online reconciliation. Basically like what Google docs gives you.
It's very well supported.
It's written in JavaScript though.
Porting to golang or running it in a golang JavaScript interpreter would work.

I think a golang port would not be too hard because it's not alot of code and golang was is now working.

**Comment by donkeysharp** [comment]
Hi @gedw99, Gocho does not support file editing on different machines. It's just a file sharing app for a local network: it has only read operations and no write operations

**Comment by gedw99** [comment]
AH got it :)

Will close....
